import module

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import datasets

In [41]:
df24 = pd.read_excel(r'B:\GitHub Repository\Analysis-of-Annual-Education-Sector-Inflation-in-Indonesia\datasets\2024.xlsx', skiprows=1)
df25 = pd.read_excel(r'B:\GitHub Repository\Analysis-of-Annual-Education-Sector-Inflation-in-Indonesia\datasets\2025.xlsx', skiprows=1)

setting row col size

In [42]:
pd.set_option('display.max.rows', 10)
pd.set_option('display.max.columns', 100)

In [43]:
df25

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,KAB ACEH TENGAH,0.07,0.07,0.28,0.1,0.52,0.79,-,-,-,-,-,-,-,0.18,0.18,0.77,0.26,1.35,2.05,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
4,MEULABOH,0.03,0.03,0.03,0.03,0.03,0.03,-,-,-,-,-,-,-,0.08,0.08,0.08,0.08,0.08,0.08,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,MERAUKE,-2.17,-2.17,-2.17,-2.17,-2.17,-2.17,-,-,-,-,-,-,-,-16.48,-16.48,-16.48,-16.48,-16.48,-16.48,-,-,-,-,-,-,-,0.62,0.62,0.62,0.62,0.62,0.62,-,-,-,-,-,-,-,11.11,11.11,11.11,11.11,11.11,11.11,-,-,-,-,-,-,-,7.38,7.38,7.38,7.38,7.38,7.38,-,-,-,-,-,-,-
150,TIMIKA,1.09,1.09,1.09,1.09,1.09,0.2,-,-,-,-,-,-,-,2.67,2.67,2.67,2.67,2.67,0.37,-,-,-,-,-,-,-,0.14,0.14,0.14,0.14,0.14,0.14,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
151,KAB NABIRE,1.96,2.3,2.3,2.3,2.3,2.3,-,-,-,-,-,-,-,0.71,0.71,0.71,0.71,0.71,0.71,-,-,-,-,-,-,-,3.81,4.74,4.74,4.74,4.74,4.74,-,-,-,-,-,-,-,1.58,1.58,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
152,KAB JAYAWIJAYA,1.82,3.15,3.15,3.15,3.15,3.15,-,-,-,-,-,-,-,2.47,2.47,2.47,2.47,2.47,2.47,-,-,-,-,-,-,-,2.15,3.95,3.95,3.95,3.95,3.95,-,-,-,-,-,-,-,0,3.69,3.69,3.69,3.69,3.69,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
153,INDONESIA,2.05,2.04,1.89,1.88,1.88,1.82,-,-,-,-,-,-,-,2.73,2.74,2.74,2.74,2.74,2.74,-,-,-,-,-,-,-,1.69,1.69,1.69,1.69,1.69,1.27,-,-,-,-,-,-,-,1.41,1.39,1.39,1.39,1.39,1.4,-,-,-,-,-,-,-,3.79,3.7,2.35,2.18,2.23,2.75,-,-,-,-,-,-,-

drop index 1 (disini index 1 = Tahun, yang dimana kurang berguna jika ditaruh di posisi itu karena tidak bisa di analisa)

In [48]:
df25.drop(df25.index[1], inplace=True)
df24.drop(df24.index[1], inplace=True)

In [54]:
df25

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,KAB ACEH TENGAH,0.07,0.07,0.28,0.1,0.52,0.79,-,-,-,-,-,-,-,0.18,0.18,0.77,0.26,1.35,2.05,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
4,MEULABOH,0.03,0.03,0.03,0.03,0.03,0.03,-,-,-,-,-,-,-,0.08,0.08,0.08,0.08,0.08,0.08,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-
5,KAB ACEH TAMIANG,5.14,5.14,5.14,5.14,5.14,5.14,-,-,-,-,-,-,-,2.13,2.13,2.13,2.13,2.13,2.13,-,-,-,-,-,-,-,1.07,1.07,1.07,1.07,1.07,1.07,-,-,-,-,-,-,-,7.81,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
6,KOTA BANDA ACEH,0.58,0.55,0.55,0.55,0.55,0.55,-,-,-,-,-,-,-,2.42,2.42,2.42,2.42,2.42,2.42,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0.38,0,0,0,0,0,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,MERAUKE,-2.17,-2.17,-2.17,-2.17,-2.17,-2.17,-,-,-,-,-,-,-,-16.48,-16.48,-16.48,-16.48,-16.48,-16.48,-,-,-,-,-,-,-,0.62,0.62,0.62,0.62,0.62,0.62,-,-,-,-,-,-,-,11.11,11.11,11.11,11.11,11.11,11.11,-,-,-,-,-,-,-,7.38,7.38,7.38,7.38,7.38,7.38,-,-,-,-,-,-,-
150,TIMIKA,1.09,1.09,1.09,1.09,1.09,0.2,-,-,-,-,-,-,-,2.67,2.67,2.67,2.67,2.67,0.37,-,-,-,-,-,-,-,0.14,0.14,0.14,0.14,0.14,0.14,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
151,KAB NABIRE,1.96,2.3,2.3,2.3,2.3,2.3,-,-,-,-,-,-,-,0.71,0.71,0.71,0.71,0.71,0.71,-,-,-,-,-,-,-,3.81,4.74,4.74,4.74,4.74,4.74,-,-,-,-,-,-,-,1.58,1.58,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
152,KAB JAYAWIJAYA,1.82,3.15,3.15,3.15,3.15,3.15,-,-,-,-,-,-,-,2.47,2.47,2.47,2.47,2.47,2.47,-,-,-,-,-,-,-,2.15,3.95,3.95,3.95,3.95,3.95,-,-,-,-,-,-,-,0,3.69,3.69,3.69,3.69,3.69,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
153,INDONESIA,2.05,2.04,1.89,1.88,1.88,1.82,-,-,-,-,-,-,-,2.73,2.74,2.74,2.74,2.74,2.74,-,-,-,-,-,-,-,1.69,1.69,1.69,1.69,1.69,1.27,-,-,-,-,-,-,-,1.41,1.39,1.39,1.39,1.39,1.4,-,-,-,-,-,-,-,3.79,3.7,2.35,2.18,2.23,2.75,-,-,-,-,-,-,-

In [55]:
df24

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,KAB ACEH TENGAH,0,0,0,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,-,0,0,0,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-
4,MEULABOH,2.79,2.26,1.81,0.7,0.7,0.7,0.7,0.7,0.73,0.73,0.66,0.66,-,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.25,2.25,2.25,2.25,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,16.68,12.22,8.57,0.49,0.49,0.49,0.49,0.49,0.49,0.49,0,0,-
5,KAB ACEH TAMIANG,2.36,2.36,2.36,2.36,2.36,2.36,1.39,4.78,5.14,5.14,5.14,5.14,-,11.49,11.49,11.49,11.49,11.49,11.49,6.52,1.53,2.13,2.13,2.13,2.13,-,0,0,0,0,0,0,0,0,1.07,1.07,1.07,1.07,-,0,0,0,0,0,0,0,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,MERAUKE,2.77,2.77,2.77,2.77,2.77,2.03,-2.88,-3.73,-2.36,-2.36,-2.36,-2.36,-,8.23,8.23,8.23,8.23,8.23,5.87,-9.54,-11.82,-17.04,-17.04,-17.04,-17.04,-,0,0,0,0,0,0,-0.67,-0.67,0.62,0.62,0.62,0.62,-,0,0,0,0,0,0,0,0,11.11,11.11,11.11,11.11,-,0.76,0.76,0.76,0.76,0.76,0.76,7.38,7.38,7.38,7.38,7.38,7.38,-
150,TIMIKA,0,0,0,0,0,0.89,1.02,1.09,1.09,1.09,1.09,1.09,-,0,0,0,0,0,2.29,2.73,2.67,2.67,2.67,2.67,2.67,-,0,0,0,0,0,0,-0.1,0.14,0.14,0.14,0.14,0.14,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-
151,KAB NABIRE,0.54,0.21,0.21,0.21,0.21,0.21,0.21,1.58,1.96,1.96,1.96,1.96,-,1.11,1.11,1.11,1.11,1.11,1.11,1.11,1.83,0.71,0.71,0.71,0.71,-,0,-0.89,-0.89,-0.89,-0.89,-0.89,-0.89,1.57,3.81,3.81,3.81,3.81,-,0,0,0,0,0,0,0,0.83,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-
152,KAB JAYAWIJAYA,0,0,0,0,0,0,1.82,1.82,1.82,1.82,1.82,1.82,-,0,0,0,0,0,0,2.47,2.47,2.47,2.47,2.47,2.47,-,0,0,0,0,0,0,2.15,2.15,2.15,2.15,2.15,2.15,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-
153,INDONESIA,1.57,1.55,1.7,1.72,1.71,1.69,1.9,1.83,1.94,1.9,1.89,1.94,-,1.77,1.76,1.76,1.76,1.75,1.66,2.1,2.68,2.74,2.72,2.72,2.72,-,1.83,1.83,1.83,1.83,1.83,1.83,1.99,1.51,1.53,1.53,1.53,1.68,-,1.08,1.1,1.1,1.1,1.1,1.1,1.22,1.03,1.33,1.36,1.36,1.36,-,2.09,1.95,3.27,3.46,3.38,3.36,3.62,3.62,3.47,3.12,3.09,3.07,-

In [56]:
df24['Tahun'] = 2024
df25['Tahun'] = 2025

In [57]:
df25

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Tahun
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025
3,KAB ACEH TENGAH,0.07,0.07,0.28,0.1,0.52,0.79,-,-,-,-,-,-,-,0.18,0.18,0.77,0.26,1.35,2.05,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
4,MEULABOH,0.03,0.03,0.03,0.03,0.03,0.03,-,-,-,-,-,-,-,0.08,0.08,0.08,0.08,0.08,0.08,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,2025
5,KAB ACEH TAMIANG,5.14,5.14,5.14,5.14,5.14,5.14,-,-,-,-,-,-,-,2.13,2.13,2.13,2.13,2.13,2.13,-,-,-,-,-,-,-,1.07,1.07,1.07,1.07,1.07,1.07,-,-,-,-,-,-,-,7.81,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
6,KOTA BANDA ACEH,0.58,0.55,0.55,0.55,0.55,0.55,-,-,-,-,-,-,-,2.42,2.42,2.42,2.42,2.42,2.42,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0.38,0,0,0,0,0,-,-,-,-,-,-,-,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,MERAUKE,-2.17,-2.17,-2.17,-2.17,-2.17,-2.17,-,-,-,-,-,-,-,-16.48,-16.48,-16.48,-16.48,-16.48,-16.48,-,-,-,-,-,-,-,0.62,0.62,0.62,0.62,0.62,0.62,-,-,-,-,-,-,-,11.11,11.11,11.11,11.11,11.11,11.11,-,-,-,-,-,-,-,7.38,7.38,7.38,7.38,7.38,7.38,-,-,-,-,-,-,-,2025
150,TIMIKA,1.09,1.09,1.09,1.09,1.09,0.2,-,-,-,-,-,-,-,2.67,2.67,2.67,2.67,2.67,0.37,-,-,-,-,-,-,-,0.14,0.14,0.14,0.14,0.14,0.14,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
151,KAB NABIRE,1.96,2.3,2.3,2.3,2.3,2.3,-,-,-,-,-,-,-,0.71,0.71,0.71,0.71,0.71,0.71,-,-,-,-,-,-,-,3.81,4.74,4.74,4.74,4.74,4.74,-,-,-,-,-,-,-,1.58,1.58,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
152,KAB JAYAWIJAYA,1.82,3.15,3.15,3.15,3.15,3.15,-,-,-,-,-,-,-,2.47,2.47,2.47,2.47,2.47,2.47,-,-,-,-,-,-,-,2.15,3.95,3.95,3.95,3.95,3.95,-,-,-,-,-,-,-,0,3.69,3.69,3.69,3.69,3.69,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
153,INDONESIA,2.05,2.04,1.89,1.88,1.88,1.82,-,-,-,-,-,-,-,2.73,2.74,2.74,2.74,2.74,2.74,-,-,-,-,-,-,-,1.69,1.69,1.69,1.69,1.69,1.27,-,-,-,-,-,-,-,1.41,1.39,1.39,1.39,1.39,1.4,-,-,-,-,-,-,-,3.79,3.7,2.35,2.18,2.23,2.75,-,-,-,-,-,-,-,2025

In [58]:
df24

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Tahun
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,2024
3,KAB ACEH TENGAH,0,0,0,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,-,0,0,0,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
4,MEULABOH,2.79,2.26,1.81,0.7,0.7,0.7,0.7,0.7,0.73,0.73,0.66,0.66,-,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.25,2.25,2.25,2.25,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,16.68,12.22,8.57,0.49,0.49,0.49,0.49,0.49,0.49,0.49,0,0,-,2024
5,KAB ACEH TAMIANG,2.36,2.36,2.36,2.36,2.36,2.36,1.39,4.78,5.14,5.14,5.14,5.14,-,11.49,11.49,11.49,11.49,11.49,11.49,6.52,1.53,2.13,2.13,2.13,2.13,-,0,0,0,0,0,0,0,0,1.07,1.07,1.07,1.07,-,0,0,0,0,0,0,0,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,MERAUKE,2.77,2.77,2.77,2.77,2.77,2.03,-2.88,-3.73,-2.36,-2.36,-2.36,-2.36,-,8.23,8.23,8.23,8.23,8.23,5.87,-9.54,-11.82,-17.04,-17.04,-17.04,-17.04,-,0,0,0,0,0,0,-0.67,-0.67,0.62,0.62,0.62,0.62,-,0,0,0,0,0,0,0,0,11.11,11.11,11.11,11.11,-,0.76,0.76,0.76,0.76,0.76,0.76,7.38,7.38,7.38,7.38,7.38,7.38,-,2024
150,TIMIKA,0,0,0,0,0,0.89,1.02,1.09,1.09,1.09,1.09,1.09,-,0,0,0,0,0,2.29,2.73,2.67,2.67,2.67,2.67,2.67,-,0,0,0,0,0,0,-0.1,0.14,0.14,0.14,0.14,0.14,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
151,KAB NABIRE,0.54,0.21,0.21,0.21,0.21,0.21,0.21,1.58,1.96,1.96,1.96,1.96,-,1.11,1.11,1.11,1.11,1.11,1.11,1.11,1.83,0.71,0.71,0.71,0.71,-,0,-0.89,-0.89,-0.89,-0.89,-0.89,-0.89,1.57,3.81,3.81,3.81,3.81,-,0,0,0,0,0,0,0,0.83,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
152,KAB JAYAWIJAYA,0,0,0,0,0,0,1.82,1.82,1.82,1.82,1.82,1.82,-,0,0,0,0,0,0,2.47,2.47,2.47,2.47,2.47,2.47,-,0,0,0,0,0,0,2.15,2.15,2.15,2.15,2.15,2.15,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
153,INDONESIA,1.57,1.55,1.7,1.72,1.71,1.69,1.9,1.83,1.94,1.9,1.89,1.94,-,1.77,1.76,1.76,1.76,1.75,1.66,2.1,2.68,2.74,2.72,2.72,2.72,-,1.83,1.83,1.83,1.83,1.83,1.83,1.99,1.51,1.53,1.53,1.53,1.68,-,1.08,1.1,1.1,1.1,1.1,1.1,1.22,1.03,1.33,1.36,1.36,1.36,-,2.09,1.95,3.27,3.46,3.38,3.36,3.62,3.62,3.47,3.12,3.09,3.07,-,2024

In [59]:
df_combined = pd.concat([df24, df25], ignore_index=True)

In [60]:
df_combined

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Tahun
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
1,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,2024
2,KAB ACEH TENGAH,0,0,0,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,-,0,0,0,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
3,MEULABOH,2.79,2.26,1.81,0.7,0.7,0.7,0.7,0.7,0.73,0.73,0.66,0.66,-,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.25,2.25,2.25,2.25,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,16.68,12.22,8.57,0.49,0.49,0.49,0.49,0.49,0.49,0.49,0,0,-,2024
4,KAB ACEH TAMIANG,2.36,2.36,2.36,2.36,2.36,2.36,1.39,4.78,5.14,5.14,5.14,5.14,-,11.49,11.49,11.49,11.49,11.49,11.49,6.52,1.53,2.13,2.13,2.13,2.13,-,0,0,0,0,0,0,0,0,1.07,1.07,1.07,1.07,-,0,0,0,0,0,0,0,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,MERAUKE,-2.17,-2.17,-2.17,-2.17,-2.17,-2.17,-,-,-,-,-,-,-,-16.48,-16.48,-16.48,-16.48,-16.48,-16.48,-,-,-,-,-,-,-,0.62,0.62,0.62,0.62,0.62,0.62,-,-,-,-,-,-,-,11.11,11.11,11.11,11.11,11.11,11.11,-,-,-,-,-,-,-,7.38,7.38,7.38,7.38,7.38,7.38,-,-,-,-,-,-,-,2025
301,TIMIKA,1.09,1.09,1.09,1.09,1.09,0.2,-,-,-,-,-,-,-,2.67,2.67,2.67,2.67,2.67,0.37,-,-,-,-,-,-,-,0.14,0.14,0.14,0.14,0.14,0.14,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
302,KAB NABIRE,1.96,2.3,2.3,2.3,2.3,2.3,-,-,-,-,-,-,-,0.71,0.71,0.71,0.71,0.71,0.71,-,-,-,-,-,-,-,3.81,4.74,4.74,4.74,4.74,4.74,-,-,-,-,-,-,-,1.58,1.58,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
303,KAB JAYAWIJAYA,1.82,3.15,3.15,3.15,3.15,3.15,-,-,-,-,-,-,-,2.47,2.47,2.47,2.47,2.47,2.47,-,-,-,-,-,-,-,2.15,3.95,3.95,3.95,3.95,3.95,-,-,-,-,-,-,-,0,3.69,3.69,3.69,3.69,3.69,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
304,INDONESIA,2.05,2.04,1.89,1.88,1.88,1.82,-,-,-,-,-,-,-,2.73,2.74,2.74,2.74,2.74,2.74,-,-,-,-,-,-,-,1.69,1.69,1.69,1.69,1.69,1.27,-,-,-,-,-,-,-,1.41,1.39,1.39,1.39,1.39,1.4,-,-,-,-,-,-,-,3.79,3.7,2.35,2.18,2.23,2.75,-,-,-,-,-,-,-,2025

In [61]:
print("Data gabungan sebelum pembersihan (5 baris pertama):")
print(df_combined.head())
print("\nData gabungan sebelum pembersihan (5 baris terakhir):")
print(df_combined.tail())

Data gabungan sebelum pembersihan (5 baris pertama):
         Unnamed: 0  \
0               NaN
1               NaN
2   KAB ACEH TENGAH
3          MEULABOH
4  KAB ACEH TAMIANG

  Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen)  \
0                                         Pendidikan
1                                            Januari
2                                                  0
3                                               2.79
4                                               2.36

  Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
0        NaN        NaN        NaN        NaN        NaN        NaN
1   Februari      Maret      April        Mei       Juni       Juli
2          0          0       0.19       0.19       0.19       0.19
3       2.26       1.81        0.7        0.7        0.7        0.7
4       2.36       2.36       2.36       2.36       2.36       1.39

  Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
0        NaN        NaN         NaN         NaN         NaN         NaN
1    Agustus  September     Oktober    November    Desember     Tahunan
2       0.19       0.19        0.19        0.19        0.19           -
3        0.7       0.73        0.73        0.66        0.66           -
4       4.78       5.14        5.14        5.14        5.14           -

                           Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17  \
0  Pendidikan Dasar dan Anak Usia Dini         NaN         NaN         NaN
1                              Januari    Februari       Maret       April
2                                    0           0           0        0.51
3                                 2.17        2.17        2.17        2.17
4                                11.49       11.49       11.49       11.49

  Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         Mei        Juni        Juli     Agustus   September     Oktober
2        0.51        0.51        0.51        0.51        0.51        0.51
3        2.17        2.17        2.17        2.17        2.25        2.25
4       11.49       11.49        6.52        1.53        2.13        2.13

  Unnamed: 24 Unnamed: 25 Unnamed: 26          Unnamed: 27 Unnamed: 28  \
0         NaN         NaN         NaN  Pendidikan Menengah         NaN
1    November    Desember     Tahunan              Januari    Februari
2        0.51        0.51           -                    0           0
3        2.25        2.25           -                    0           0
4        2.13        2.13           -                    0           0

  Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32 Unnamed: 33 Unnamed: 34  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1       Maret       April         Mei        Juni        Juli     Agustus
2           0           0           0           0           0           0
3           0           0           0           0           0           0
4           0           0           0           0           0           0

  Unnamed: 35 Unnamed: 36 Unnamed: 37 Unnamed: 38 Unnamed: 39  \
0         NaN         NaN         NaN         NaN         NaN
1   September     Oktober    November    Desember     Tahunan
2           0           0           0           0           -
3           0           0           0           0           -
4        1.07        1.07        1.07        1.07           -

         Unnamed: 40 Unnamed: 41 Unnamed: 42 Unnamed: 43 Unnamed: 44  \
0  Pendidikan Tinggi         NaN         NaN         NaN         NaN
1            Januari    Februari       Maret       April         Mei
2                  0           0           0           0           0
3                  0           0           0           0           0
4                  0           0           0           0           0

  Unnamed: 45 Unnamed: 46 Unnamed: 47 Unnamed: 48 Unnamed: 49 Unnamed: 50  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1        Juni        Juli     Agustus   September     Oktober    November
2           0           0           0           0           0           0
3           0           0           0           0           0           0
4           0           0        7.81        7.81        7.81        7.81

  Unnamed: 51 Unnamed: 52         Unnamed: 53 Unnamed: 54 Unnamed: 55  \
0         NaN         NaN  Pendidikan Lainnya         NaN         NaN
1    Desember     Tahunan             Januari    Februari       Maret
2           0           -                   -           -           -
3           0           -               16.68       12.22        8.57
4        7.81           -                   -           -           -

  Unnamed: 56 Unnamed: 57 Unnamed: 58 Unnamed: 59 Unnamed: 60 Unnamed: 61  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1       April         Mei        Juni        Juli     Agustus   September
2           -           -           -           -           -           -
3        0.49        0.49        0.49        0.49        0.49        0.49
4           -           -           -           -           -           -

  Unnamed: 62 Unnamed: 63 Unnamed: 64 Unnamed: 65  Tahun
0         NaN         NaN         NaN         NaN   2024
1     Oktober    November    Desember     Tahunan   2024
2           -           -           -           -   2024
3        0.49           0           0           -   2024
4           -           -           -           -   2024

Data gabungan sebelum pembersihan (5 baris terakhir):
         Unnamed: 0  \
300         MERAUKE
301          TIMIKA
302      KAB NABIRE
303  KAB JAYAWIJAYA
304       INDONESIA

    Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen)  \
300                                              -2.17
301                                               1.09
302                                               1.96
303                                               1.82
304                                               2.05

    Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
300      -2.17      -2.17      -2.17      -2.17      -2.17          -
301       1.09       1.09       1.09       1.09        0.2          -
302        2.3        2.3        2.3        2.3        2.3          -
303       3.15       3.15       3.15       3.15       3.15          -
304       2.04       1.89       1.88       1.88       1.82          -

    Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
300          -          -           -           -           -           -
301          -          -           -           -           -           -
302          -          -           -           -           -           -
303          -          -           -           -           -           -
304          -          -           -           -           -           -

    Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17 Unnamed: 18 Unnamed: 19  \
300      -16.48      -16.48      -16.48      -16.48      -16.48      -16.48
301        2.67        2.67        2.67        2.67        2.67        0.37
302        0.71        0.71        0.71        0.71        0.71        0.71
303        2.47        2.47        2.47        2.47        2.47        2.47
304        2.73        2.74        2.74        2.74        2.74        2.74

    Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25  \
300           -           -           -           -           -           -
301           -           -           -           -           -           -
302           -           -           -           -           -           -
303           -           -           -           -           -           -
304           -           -           -           -           -           -

    Unnamed: 26 Unnamed: 27 Unnamed: 28 Unnamed: 29 Unnamed: 30 Unnamed: 31  \
300           -        0.62        0.62        0.62        0.62        0.62
301           -        0.14        0.14        0.14        0.14        0.14
302           -        3.81        4.74        4.74        4.74        4.74
303           -        2.15        3.95        3.95        3.95        3.95
304           -        1.69        1.69        1.69        1.69        1.69

    Unnamed: 32 Unnamed: 33 Unnamed: 34 Unnamed: 35 Unnamed: 36 Unnamed: 37  \
300        0.62           -           -           -           -           -
301        0.14           -           -           -           -           -
302        4.74           -           -           -           -           -
303        3.95           -           -           -           -           -
304        1.27           -           -           -           -           -

    Unnamed: 38 Unnamed: 39 Unnamed: 40 Unnamed: 41 Unnamed: 42 Unnamed: 43  \
300           -           -       11.11       11.11       11.11       11.11
301           -           -           0           0           0           0
302           -           -        1.58        1.58        1.58        1.58
303           -           -           0        3.69        3.69        3.69
304           -           -        1.41        1.39        1.39        1.39

    Unnamed: 44 Unnamed: 45 Unnamed: 46 Unnamed: 47 Unnamed: 48 Unnamed: 49  \
300       11.11       11.11           -           -           -           -
301           0           0           -           -           -           -
302        1.58        1.58           -           -           -           -
303        3.69        3.69           -           -           -           -
304        1.39         1.4           -           -           -           -

    Unnamed: 50 Unnamed: 51 Unnamed: 52 Unnamed: 53 Unnamed: 54 Unnamed: 55  \
300           -           -           -        7.38        7.38        7.38
301           -           -           -           -           -           -
302           -           -           -           -           -           -
303           -           -           -           -           -           -
304           -           -           -        3.79         3.7        2.35

    Unnamed: 56 Unnamed: 57 Unnamed: 58 Unnamed: 59 Unnamed: 60 Unnamed: 61  \
300        7.38        7.38        7.38           -           -           -
301           -           -           -           -           -           -
302           -           -           -           -           -           -
303           -           -           -           -           -           -
304        2.18        2.23        2.75           -           -           -

    Unnamed: 62 Unnamed: 63 Unnamed: 64 Unnamed: 65  Tahun
300           -           -           -           -   2025
301           -           -           -           -   2025
302           -           -           -           -   2025
303           -           -           -           -   2025
304           -           -           -           -   2025

In [62]:
kolom_bulan = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
               'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember']

In [ ]:
kolom_bulan_exist = [col for col in kolom_bulan if col in df_combined.columns]

[]

In [65]:
df_combined = pd.concat([df24, df25], ignore_index=True)