In [64]:
import pandas as pd

In [65]:
df24 = pd.read_excel(r'B:\GitHub Repository\Analysis-of-Annual-Education-Sector-Inflation-in-Indonesia\datasets\2024.xlsx', skiprows=1)
df25 = pd.read_excel(r'B:\GitHub Repository\Analysis-of-Annual-Education-Sector-Inflation-in-Indonesia\datasets\2025.xlsx', skiprows=1)

In [66]:
pd.set_option('display.max.rows', 10)
pd.set_option('display.max.columns', 100)

In [67]:
print(df25)
print(df24)

          Unnamed: 0  \
0                NaN
1                NaN
2                NaN
3    KAB ACEH TENGAH
4           MEULABOH
..               ...
149          MERAUKE
150           TIMIKA
151       KAB NABIRE
152   KAB JAYAWIJAYA
153        INDONESIA

    Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen)  \
0                                           Pendidikan
1                                                 2025
2                                              Januari
3                                                 0.07
4                                                 0.03
..                                                 ...
149                                              -2.17
150                                               1.09
151                                               1.96
152                                               1.82
153                                               2.05

    Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
0          NaN        NaN        NaN        NaN        NaN        NaN
1          NaN        NaN        NaN        NaN        NaN        NaN
2     Februari      Maret      April        Mei       Juni       Juli
3         0.07       0.28        0.1       0.52       0.79          -
4         0.03       0.03       0.03       0.03       0.03          -
..         ...        ...        ...        ...        ...        ...
149      -2.17      -2.17      -2.17      -2.17      -2.17          -
150       1.09       1.09       1.09       1.09        0.2          -
151        2.3        2.3        2.3        2.3        2.3          -
152       3.15       3.15       3.15       3.15       3.15          -
153       2.04       1.89       1.88       1.88       1.82          -

    Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
0          NaN        NaN         NaN         NaN         NaN         NaN
1          NaN        NaN         NaN         NaN         NaN         NaN
2      Agustus  September     Oktober    November    Desember     Tahunan
3            -          -           -           -           -           -
4            -          -           -           -           -           -
..         ...        ...         ...         ...         ...         ...
149          -          -           -           -           -           -
150          -          -           -           -           -           -
151          -          -           -           -           -           -
152          -          -           -           -           -           -
153          -          -           -           -           -           -

                             Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17  \
0    Pendidikan Dasar dan Anak Usia Dini         NaN         NaN         NaN
1                                   2025         NaN         NaN         NaN
2                                Januari    Februari       Maret       April
3                                   0.18        0.18        0.77        0.26
4                                   0.08        0.08        0.08        0.08
..                                   ...         ...         ...         ...
149                               -16.48      -16.48      -16.48      -16.48
150                                 2.67        2.67        2.67        2.67
151                                 0.71        0.71        0.71        0.71
152                                 2.47        2.47        2.47        2.47
153                                 2.73        2.74        2.74        2.74

    Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2           Mei        Juni        Juli     Agustus   September     Oktober
3          1.35        2.05           -           -           -           -
4          0.08        0.08           -           -           -           -
..          ...         ...         ...         ...         ...         ...
149      -16.48      -16.48           -           -           -           -
150        2.67        0.37           -           -           -           -
151        0.71        0.71           -           -           -           -
152        2.47        2.47           -           -           -           -
153        2.74        2.74           -           -           -           -

    Unnamed: 24 Unnamed: 25 Unnamed: 26          Unnamed: 27 Unnamed: 28  \
0           NaN         NaN         NaN  Pendidikan Menengah         NaN
1           NaN         NaN         NaN                 2025         NaN
2      November    Desember     Tahunan              Januari    Februari
3             -           -           -                    0           0
4             -           -           -                    0           0
..          ...         ...         ...                  ...         ...
149           -           -           -                 0.62        0.62
150           -           -           -                 0.14        0.14
151           -           -           -                 3.81        4.74
152           -           -           -                 2.15        3.95
153           -           -           -                 1.69        1.69

    Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32 Unnamed: 33 Unnamed: 34  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2         Maret       April         Mei        Juni        Juli     Agustus
3             0           0           0           0           -           -
4             0           0           0           0           -           -
..          ...         ...         ...         ...         ...         ...
149        0.62        0.62        0.62        0.62           -           -
150        0.14        0.14        0.14        0.14           -           -
151        4.74        4.74        4.74        4.74           -           -
152        3.95        3.95        3.95        3.95           -           -
153        1.69        1.69        1.69        1.27           -           -

    Unnamed: 35 Unnamed: 36 Unnamed: 37 Unnamed: 38 Unnamed: 39  \
0           NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN
2     September     Oktober    November    Desember     Tahunan
3             -           -           -           -           -
4             -           -           -           -           -
..          ...         ...         ...         ...         ...
149           -           -           -           -           -
150           -           -           -           -           -
151           -           -           -           -           -
152           -           -           -           -           -
153           -           -           -           -           -

           Unnamed: 40 Unnamed: 41 Unnamed: 42 Unnamed: 43 Unnamed: 44  \
0    Pendidikan Tinggi         NaN         NaN         NaN         NaN
1                 2025         NaN         NaN         NaN         NaN
2              Januari    Februari       Maret       April         Mei
3                    0           0           0           0           0
4                    0           0           0           0           0
..                 ...         ...         ...         ...         ...
149              11.11       11.11       11.11       11.11       11.11
150                  0           0           0           0           0
151               1.58        1.58        1.58        1.58        1.58
152                  0        3.69        3.69        3.69        3.69
153               1.41        1.39        1.39        1.39        1.39

    Unnamed: 45 Unnamed: 46 Unnamed: 47 Unnamed: 48 Unnamed: 49 Unnamed: 50  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2          Juni        Juli     Agustus   September     Oktober    November
3             0           -           -           -           -           -
4             0           -           -           -           -           -
..          ...         ...         ...         ...         ...         ...
149       11.11           -           -           -           -           -
150           0           -           -           -           -           -
151        1.58           -           -           -           -           -
152        3.69           -           -           -           -           -
153         1.4           -           -           -           -           -

    Unnamed: 51 Unnamed: 52         Unnamed: 53 Unnamed: 54 Unnamed: 55  \
0           NaN         NaN  Pendidikan Lainnya         NaN         NaN
1           NaN         NaN                2025         NaN         NaN
2      Desember     Tahunan             Januari    Februari       Maret
3             -           -                   -           -           -
4             -           -                   0           0           0
..          ...         ...                 ...         ...         ...
149           -           -                7.38        7.38        7.38
150           -           -                   -           -           -
151           -           -                   -           -           -
152           -           -                   -           -           -
153           -           -                3.79         3.7        2.35

    Unnamed: 56 Unnamed: 57 Unnamed: 58 Unnamed: 59 Unnamed: 60 Unnamed: 61  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2         April         Mei        Juni        Juli     Agustus   September
3             -           -           -           -           -           -
4             0           0           0           -           -           -
..          ...         ...         ...         ...         ...         ...
149        7.38        7.38        7.38           -           -           -
150           -           -           -           -           -           -
151           -           -           -           -           -           -
152           -           -           -           -           -           -
153        2.18        2.23        2.75           -           -           -

    Unnamed: 62 Unnamed: 63 Unnamed: 64 Unnamed: 65
0           NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN
2       Oktober    November    Desember     Tahunan
3             -           -           -           -
4             -           -           -           -
..          ...         ...         ...         ...
149           -           -           -           -
150           -           -           -           -
151           -           -           -           -
152           -           -           -           -
153           -           -           -           -

[154 rows x 66 columns]
          Unnamed: 0  \
0                NaN
1                NaN
2                NaN
3    KAB ACEH TENGAH
4           MEULABOH
..               ...
149          MERAUKE
150           TIMIKA
151       KAB NABIRE
152   KAB JAYAWIJAYA
153        INDONESIA

    Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen)  \
0                                           Pendidikan
1                                                 2024
2                                              Januari
3                                                    0
4                                                 2.79
..                                                 ...
149                                               2.77
150                                                  0
151                                               0.54
152                                                  0
153                                               1.57

    Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
0          NaN        NaN        NaN        NaN        NaN        NaN
1          NaN        NaN        NaN        NaN        NaN        NaN
2     Februari      Maret      April        Mei       Juni       Juli
3            0          0       0.19       0.19       0.19       0.19
4         2.26       1.81        0.7        0.7        0.7        0.7
..         ...        ...        ...        ...        ...        ...
149       2.77       2.77       2.77       2.77       2.03      -2.88
150          0          0          0          0       0.89       1.02
151       0.21       0.21       0.21       0.21       0.21       0.21
152          0          0          0          0          0       1.82
153       1.55        1.7       1.72       1.71       1.69        1.9

    Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
0          NaN        NaN         NaN         NaN         NaN         NaN
1          NaN        NaN         NaN         NaN         NaN         NaN
2      Agustus  September     Oktober    November    Desember     Tahunan
3         0.19       0.19        0.19        0.19        0.19           -
4          0.7       0.73        0.73        0.66        0.66           -
..         ...        ...         ...         ...         ...         ...
149      -3.73      -2.36       -2.36       -2.36       -2.36           -
150       1.09       1.09        1.09        1.09        1.09           -
151       1.58       1.96        1.96        1.96        1.96           -
152       1.82       1.82        1.82        1.82        1.82           -
153       1.83       1.94         1.9        1.89        1.94           -

                             Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17  \
0    Pendidikan Dasar dan Anak Usia Dini         NaN         NaN         NaN
1                                   2024         NaN         NaN         NaN
2                                Januari    Februari       Maret       April
3                                      0           0           0        0.51
4                                   2.17        2.17        2.17        2.17
..                                   ...         ...         ...         ...
149                                 8.23        8.23        8.23        8.23
150                                    0           0           0           0
151                                 1.11        1.11        1.11        1.11
152                                    0           0           0           0
153                                 1.77        1.76        1.76        1.76

    Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2           Mei        Juni        Juli     Agustus   September     Oktober
3          0.51        0.51        0.51        0.51        0.51        0.51
4          2.17        2.17        2.17        2.17        2.25        2.25
..          ...         ...         ...         ...         ...         ...
149        8.23        5.87       -9.54      -11.82      -17.04      -17.04
150           0        2.29        2.73        2.67        2.67        2.67
151        1.11        1.11        1.11        1.83        0.71        0.71
152           0           0        2.47        2.47        2.47        2.47
153        1.75        1.66         2.1        2.68        2.74        2.72

    Unnamed: 24 Unnamed: 25 Unnamed: 26          Unnamed: 27 Unnamed: 28  \
0           NaN         NaN         NaN  Pendidikan Menengah         NaN
1           NaN         NaN         NaN                 2024         NaN
2      November    Desember     Tahunan              Januari    Februari
3          0.51        0.51           -                    0           0
4          2.25        2.25           -                    0           0
..          ...         ...         ...                  ...         ...
149      -17.04      -17.04           -                    0           0
150        2.67        2.67           -                    0           0
151        0.71        0.71           -                    0       -0.89
152        2.47        2.47           -                    0           0
153        2.72        2.72           -                 1.83        1.83

    Unnamed: 29 Unnamed: 30 Unnamed: 31 Unnamed: 32 Unnamed: 33 Unnamed: 34  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2         Maret       April         Mei        Juni        Juli     Agustus
3             0           0           0           0           0           0
4             0           0           0           0           0           0
..          ...         ...         ...         ...         ...         ...
149           0           0           0           0       -0.67       -0.67
150           0           0           0           0        -0.1        0.14
151       -0.89       -0.89       -0.89       -0.89       -0.89        1.57
152           0           0           0           0        2.15        2.15
153        1.83        1.83        1.83        1.83        1.99        1.51

    Unnamed: 35 Unnamed: 36 Unnamed: 37 Unnamed: 38 Unnamed: 39  \
0           NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN
2     September     Oktober    November    Desember     Tahunan
3             0           0           0           0           -
4             0           0           0           0           -
..          ...         ...         ...         ...         ...
149        0.62        0.62        0.62        0.62           -
150        0.14        0.14        0.14        0.14           -
151        3.81        3.81        3.81        3.81           -
152        2.15        2.15        2.15        2.15           -
153        1.53        1.53        1.53        1.68           -

           Unnamed: 40 Unnamed: 41 Unnamed: 42 Unnamed: 43 Unnamed: 44  \
0    Pendidikan Tinggi         NaN         NaN         NaN         NaN
1                 2024         NaN         NaN         NaN         NaN
2              Januari    Februari       Maret       April         Mei
3                    0           0           0           0           0
4                    0           0           0           0           0
..                 ...         ...         ...         ...         ...
149                  0           0           0           0           0
150                  0           0           0           0           0
151                  0           0           0           0           0
152                  0           0           0           0           0
153               1.08         1.1         1.1         1.1         1.1

    Unnamed: 45 Unnamed: 46 Unnamed: 47 Unnamed: 48 Unnamed: 49 Unnamed: 50  \
0           NaN         NaN         NaN         NaN         NaN         NaN
1           NaN         NaN         NaN         NaN         NaN         NaN
2          Juni        Juli     Agustus   September     Oktober    November
3             0           0           0           0           0           0
4             0           0           0           0           0           0
..          ...         ...         ...         ...         ...         ...
149           0           0           0       11.11       11.11       11.11
150           0           0           0           0           0           0

In [68]:
df25.drop(df25.index[1], inplace=True)
df24.drop(df24.index[1], inplace=True)

In [69]:
df25

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
3,KAB ACEH TENGAH,0.07,0.07,0.28,0.1,0.52,0.79,-,-,-,-,-,-,-,0.18,0.18,0.77,0.26,1.35,2.05,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
4,MEULABOH,0.03,0.03,0.03,0.03,0.03,0.03,-,-,-,-,-,-,-,0.08,0.08,0.08,0.08,0.08,0.08,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-
5,KAB ACEH TAMIANG,5.14,5.14,5.14,5.14,5.14,5.14,-,-,-,-,-,-,-,2.13,2.13,2.13,2.13,2.13,2.13,-,-,-,-,-,-,-,1.07,1.07,1.07,1.07,1.07,1.07,-,-,-,-,-,-,-,7.81,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,MERAUKE,-2.17,-2.17,-2.17,-2.17,-2.17,-2.17,-,-,-,-,-,-,-,-16.48,-16.48,-16.48,-16.48,-16.48,-16.48,-,-,-,-,-,-,-,0.62,0.62,0.62,0.62,0.62,0.62,-,-,-,-,-,-,-,11.11,11.11,11.11,11.11,11.11,11.11,-,-,-,-,-,-,-,7.38,7.38,7.38,7.38,7.38,7.38,-,-,-,-,-,-,-
150,TIMIKA,1.09,1.09,1.09,1.09,1.09,0.2,-,-,-,-,-,-,-,2.67,2.67,2.67,2.67,2.67,0.37,-,-,-,-,-,-,-,0.14,0.14,0.14,0.14,0.14,0.14,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
151,KAB NABIRE,1.96,2.3,2.3,2.3,2.3,2.3,-,-,-,-,-,-,-,0.71,0.71,0.71,0.71,0.71,0.71,-,-,-,-,-,-,-,3.81,4.74,4.74,4.74,4.74,4.74,-,-,-,-,-,-,-,1.58,1.58,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
152,KAB JAYAWIJAYA,1.82,3.15,3.15,3.15,3.15,3.15,-,-,-,-,-,-,-,2.47,2.47,2.47,2.47,2.47,2.47,-,-,-,-,-,-,-,2.15,3.95,3.95,3.95,3.95,3.95,-,-,-,-,-,-,-,0,3.69,3.69,3.69,3.69,3.69,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
153,INDONESIA,2.05,2.04,1.89,1.88,1.88,1.82,-,-,-,-,-,-,-,2.73,2.74,2.74,2.74,2.74,2.74,-,-,-,-,-,-,-,1.69,1.69,1.69,1.69,1.69,1.27,-,-,-,-,-,-,-,1.41,1.39,1.39,1.39,1.39,1.4,-,-,-,-,-,-,-,3.79,3.7,2.35,2.18,2.23,2.75,-,-,-,-,-,-,-

In [70]:
df25.reset_index(drop=True, inplace=True)
df24.reset_index(drop=True, inplace=True)

In [71]:
df25

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan
2,KAB ACEH TENGAH,0.07,0.07,0.28,0.1,0.52,0.79,-,-,-,-,-,-,-,0.18,0.18,0.77,0.26,1.35,2.05,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
3,MEULABOH,0.03,0.03,0.03,0.03,0.03,0.03,-,-,-,-,-,-,-,0.08,0.08,0.08,0.08,0.08,0.08,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-
4,KAB ACEH TAMIANG,5.14,5.14,5.14,5.14,5.14,5.14,-,-,-,-,-,-,-,2.13,2.13,2.13,2.13,2.13,2.13,-,-,-,-,-,-,-,1.07,1.07,1.07,1.07,1.07,1.07,-,-,-,-,-,-,-,7.81,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,MERAUKE,-2.17,-2.17,-2.17,-2.17,-2.17,-2.17,-,-,-,-,-,-,-,-16.48,-16.48,-16.48,-16.48,-16.48,-16.48,-,-,-,-,-,-,-,0.62,0.62,0.62,0.62,0.62,0.62,-,-,-,-,-,-,-,11.11,11.11,11.11,11.11,11.11,11.11,-,-,-,-,-,-,-,7.38,7.38,7.38,7.38,7.38,7.38,-,-,-,-,-,-,-
149,TIMIKA,1.09,1.09,1.09,1.09,1.09,0.2,-,-,-,-,-,-,-,2.67,2.67,2.67,2.67,2.67,0.37,-,-,-,-,-,-,-,0.14,0.14,0.14,0.14,0.14,0.14,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
150,KAB NABIRE,1.96,2.3,2.3,2.3,2.3,2.3,-,-,-,-,-,-,-,0.71,0.71,0.71,0.71,0.71,0.71,-,-,-,-,-,-,-,3.81,4.74,4.74,4.74,4.74,4.74,-,-,-,-,-,-,-,1.58,1.58,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
151,KAB JAYAWIJAYA,1.82,3.15,3.15,3.15,3.15,3.15,-,-,-,-,-,-,-,2.47,2.47,2.47,2.47,2.47,2.47,-,-,-,-,-,-,-,2.15,3.95,3.95,3.95,3.95,3.95,-,-,-,-,-,-,-,0,3.69,3.69,3.69,3.69,3.69,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
152,INDONESIA,2.05,2.04,1.89,1.88,1.88,1.82,-,-,-,-,-,-,-,2.73,2.74,2.74,2.74,2.74,2.74,-,-,-,-,-,-,-,1.69,1.69,1.69,1.69,1.69,1.27,-,-,-,-,-,-,-,1.41,1.39,1.39,1.39,1.39,1.4,-,-,-,-,-,-,-,3.79,3.7,2.35,2.18,2.23,2.75,-,-,-,-,-,-,-

In [72]:
df24['Tahun'] = 2024
df25['Tahun'] = 2025

In [73]:
df25

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Tahun
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025
1,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,2025
2,KAB ACEH TENGAH,0.07,0.07,0.28,0.1,0.52,0.79,-,-,-,-,-,-,-,0.18,0.18,0.77,0.26,1.35,2.05,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
3,MEULABOH,0.03,0.03,0.03,0.03,0.03,0.03,-,-,-,-,-,-,-,0.08,0.08,0.08,0.08,0.08,0.08,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,2025
4,KAB ACEH TAMIANG,5.14,5.14,5.14,5.14,5.14,5.14,-,-,-,-,-,-,-,2.13,2.13,2.13,2.13,2.13,2.13,-,-,-,-,-,-,-,1.07,1.07,1.07,1.07,1.07,1.07,-,-,-,-,-,-,-,7.81,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,MERAUKE,-2.17,-2.17,-2.17,-2.17,-2.17,-2.17,-,-,-,-,-,-,-,-16.48,-16.48,-16.48,-16.48,-16.48,-16.48,-,-,-,-,-,-,-,0.62,0.62,0.62,0.62,0.62,0.62,-,-,-,-,-,-,-,11.11,11.11,11.11,11.11,11.11,11.11,-,-,-,-,-,-,-,7.38,7.38,7.38,7.38,7.38,7.38,-,-,-,-,-,-,-,2025
149,TIMIKA,1.09,1.09,1.09,1.09,1.09,0.2,-,-,-,-,-,-,-,2.67,2.67,2.67,2.67,2.67,0.37,-,-,-,-,-,-,-,0.14,0.14,0.14,0.14,0.14,0.14,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
150,KAB NABIRE,1.96,2.3,2.3,2.3,2.3,2.3,-,-,-,-,-,-,-,0.71,0.71,0.71,0.71,0.71,0.71,-,-,-,-,-,-,-,3.81,4.74,4.74,4.74,4.74,4.74,-,-,-,-,-,-,-,1.58,1.58,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
151,KAB JAYAWIJAYA,1.82,3.15,3.15,3.15,3.15,3.15,-,-,-,-,-,-,-,2.47,2.47,2.47,2.47,2.47,2.47,-,-,-,-,-,-,-,2.15,3.95,3.95,3.95,3.95,3.95,-,-,-,-,-,-,-,0,3.69,3.69,3.69,3.69,3.69,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
152,INDONESIA,2.05,2.04,1.89,1.88,1.88,1.82,-,-,-,-,-,-,-,2.73,2.74,2.74,2.74,2.74,2.74,-,-,-,-,-,-,-,1.69,1.69,1.69,1.69,1.69,1.27,-,-,-,-,-,-,-,1.41,1.39,1.39,1.39,1.39,1.4,-,-,-,-,-,-,-,3.79,3.7,2.35,2.18,2.23,2.75,-,-,-,-,-,-,-,2025

In [74]:
df_combined = pd.concat([df24, df25], ignore_index=True)
df_combined

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Tahun
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
1,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,2024
2,KAB ACEH TENGAH,0,0,0,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,-,0,0,0,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
3,MEULABOH,2.79,2.26,1.81,0.7,0.7,0.7,0.7,0.7,0.73,0.73,0.66,0.66,-,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.25,2.25,2.25,2.25,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,16.68,12.22,8.57,0.49,0.49,0.49,0.49,0.49,0.49,0.49,0,0,-,2024
4,KAB ACEH TAMIANG,2.36,2.36,2.36,2.36,2.36,2.36,1.39,4.78,5.14,5.14,5.14,5.14,-,11.49,11.49,11.49,11.49,11.49,11.49,6.52,1.53,2.13,2.13,2.13,2.13,-,0,0,0,0,0,0,0,0,1.07,1.07,1.07,1.07,-,0,0,0,0,0,0,0,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,MERAUKE,-2.17,-2.17,-2.17,-2.17,-2.17,-2.17,-,-,-,-,-,-,-,-16.48,-16.48,-16.48,-16.48,-16.48,-16.48,-,-,-,-,-,-,-,0.62,0.62,0.62,0.62,0.62,0.62,-,-,-,-,-,-,-,11.11,11.11,11.11,11.11,11.11,11.11,-,-,-,-,-,-,-,7.38,7.38,7.38,7.38,7.38,7.38,-,-,-,-,-,-,-,2025
302,TIMIKA,1.09,1.09,1.09,1.09,1.09,0.2,-,-,-,-,-,-,-,2.67,2.67,2.67,2.67,2.67,0.37,-,-,-,-,-,-,-,0.14,0.14,0.14,0.14,0.14,0.14,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
303,KAB NABIRE,1.96,2.3,2.3,2.3,2.3,2.3,-,-,-,-,-,-,-,0.71,0.71,0.71,0.71,0.71,0.71,-,-,-,-,-,-,-,3.81,4.74,4.74,4.74,4.74,4.74,-,-,-,-,-,-,-,1.58,1.58,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
304,KAB JAYAWIJAYA,1.82,3.15,3.15,3.15,3.15,3.15,-,-,-,-,-,-,-,2.47,2.47,2.47,2.47,2.47,2.47,-,-,-,-,-,-,-,2.15,3.95,3.95,3.95,3.95,3.95,-,-,-,-,-,-,-,0,3.69,3.69,3.69,3.69,3.69,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
305,INDONESIA,2.05,2.04,1.89,1.88,1.88,1.82,-,-,-,-,-,-,-,2.73,2.74,2.74,2.74,2.74,2.74,-,-,-,-,-,-,-,1.69,1.69,1.69,1.69,1.69,1.27,-,-,-,-,-,-,-,1.41,1.39,1.39,1.39,1.39,1.4,-,-,-,-,-,-,-,3.79,3.7,2.35,2.18,2.23,2.75,-,-,-,-,-,-,-,2025

In [75]:
df_combined.iloc[0:2].fillna('', inplace=True)

C:\Users\Asus\AppData\Local\Temp\ipykernel_7084\3301295546.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_combined.iloc[0:2].fillna('', inplace=True)
C:\Users\Asus\AppData\Local\Temp\ipykernel_7084\3301295546.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_combined.iloc[0:2].fillna('', inplace=True)

In [76]:
df_combined

,Unnamed: 0,Inflasi Tahunan (Y-on-Y) (2022=100) Menurut Kelompok dan Sub Kelompok 09 Pendidikan (Persen),Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Tahun
0,,Pendidikan,,,,,,,,,,,,,Pendidikan Dasar dan Anak Usia Dini,,,,,,,,,,,,,Pendidikan Menengah,,,,,,,,,,,,,Pendidikan Tinggi,,,,,,,,,,,,,Pendidikan Lainnya,,,,,,,,,,,,,2024
1,,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,2024
2,KAB ACEH TENGAH,0,0,0,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,-,0,0,0,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
3,MEULABOH,2.79,2.26,1.81,0.7,0.7,0.7,0.7,0.7,0.73,0.73,0.66,0.66,-,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.25,2.25,2.25,2.25,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,16.68,12.22,8.57,0.49,0.49,0.49,0.49,0.49,0.49,0.49,0,0,-,2024
4,KAB ACEH TAMIANG,2.36,2.36,2.36,2.36,2.36,2.36,1.39,4.78,5.14,5.14,5.14,5.14,-,11.49,11.49,11.49,11.49,11.49,11.49,6.52,1.53,2.13,2.13,2.13,2.13,-,0,0,0,0,0,0,0,0,1.07,1.07,1.07,1.07,-,0,0,0,0,0,0,0,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,MERAUKE,-2.17,-2.17,-2.17,-2.17,-2.17,-2.17,-,-,-,-,-,-,-,-16.48,-16.48,-16.48,-16.48,-16.48,-16.48,-,-,-,-,-,-,-,0.62,0.62,0.62,0.62,0.62,0.62,-,-,-,-,-,-,-,11.11,11.11,11.11,11.11,11.11,11.11,-,-,-,-,-,-,-,7.38,7.38,7.38,7.38,7.38,7.38,-,-,-,-,-,-,-,2025
302,TIMIKA,1.09,1.09,1.09,1.09,1.09,0.2,-,-,-,-,-,-,-,2.67,2.67,2.67,2.67,2.67,0.37,-,-,-,-,-,-,-,0.14,0.14,0.14,0.14,0.14,0.14,-,-,-,-,-,-,-,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
303,KAB NABIRE,1.96,2.3,2.3,2.3,2.3,2.3,-,-,-,-,-,-,-,0.71,0.71,0.71,0.71,0.71,0.71,-,-,-,-,-,-,-,3.81,4.74,4.74,4.74,4.74,4.74,-,-,-,-,-,-,-,1.58,1.58,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
304,KAB JAYAWIJAYA,1.82,3.15,3.15,3.15,3.15,3.15,-,-,-,-,-,-,-,2.47,2.47,2.47,2.47,2.47,2.47,-,-,-,-,-,-,-,2.15,3.95,3.95,3.95,3.95,3.95,-,-,-,-,-,-,-,0,3.69,3.69,3.69,3.69,3.69,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2025
305,INDONESIA,2.05,2.04,1.89,1.88,1.88,1.82,-,-,-,-,-,-,-,2.73,2.74,2.74,2.74,2.74,2.74,-,-,-,-,-,-,-,1.69,1.69,1.69,1.69,1.69,1.27,-,-,-,-,-,-,-,1.41,1.39,1.39,1.39,1.39,1.4,-,-,-,-,-,-,-,3.79,3.7,2.35,2.18,2.23,2.75,-,-,-,-,-,-,-,2025

In [77]:
df24.columns = df24.iloc[1]
df25.columns = df25.iloc[1]
df24 = df24[0:]
df25 = df24[0:]

In [78]:
df25

1,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,2024
0,NaN,Pendidikan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Dasar dan Anak Usia Dini,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Menengah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Tinggi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pendidikan Lainnya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024
1,NaN,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,Januari,Februari,Maret,April,Mei,Juni,Juli,Agustus,September,Oktober,November,Desember,Tahunan,2024
2,KAB ACEH TENGAH,0,0,0,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,0.19,-,0,0,0,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,0.51,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
3,MEULABOH,2.79,2.26,1.81,0.7,0.7,0.7,0.7,0.7,0.73,0.73,0.66,0.66,-,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.17,2.25,2.25,2.25,2.25,-,0,0,0,0,0,0,0,0,0,0,0,0,-,0,0,0,0,0,0,0,0,0,0,0,0,-,16.68,12.22,8.57,0.49,0.49,0.49,0.49,0.49,0.49,0.49,0,0,-,2024
4,KAB ACEH TAMIANG,2.36,2.36,2.36,2.36,2.36,2.36,1.39,4.78,5.14,5.14,5.14,5.14,-,11.49,11.49,11.49,11.49,11.49,11.49,6.52,1.53,2.13,2.13,2.13,2.13,-,0,0,0,0,0,0,0,0,1.07,1.07,1.07,1.07,-,0,0,0,0,0,0,0,7.81,7.81,7.81,7.81,7.81,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,MERAUKE,2.77,2.77,2.77,2.77,2.77,2.03,-2.88,-3.73,-2.36,-2.36,-2.36,-2.36,-,8.23,8.23,8.23,8.23,8.23,5.87,-9.54,-11.82,-17.04,-17.04,-17.04,-17.04,-,0,0,0,0,0,0,-0.67,-0.67,0.62,0.62,0.62,0.62,-,0,0,0,0,0,0,0,0,11.11,11.11,11.11,11.11,-,0.76,0.76,0.76,0.76,0.76,0.76,7.38,7.38,7.38,7.38,7.38,7.38,-,2024
149,TIMIKA,0,0,0,0,0,0.89,1.02,1.09,1.09,1.09,1.09,1.09,-,0,0,0,0,0,2.29,2.73,2.67,2.67,2.67,2.67,2.67,-,0,0,0,0,0,0,-0.1,0.14,0.14,0.14,0.14,0.14,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
150,KAB NABIRE,0.54,0.21,0.21,0.21,0.21,0.21,0.21,1.58,1.96,1.96,1.96,1.96,-,1.11,1.11,1.11,1.11,1.11,1.11,1.11,1.83,0.71,0.71,0.71,0.71,-,0,-0.89,-0.89,-0.89,-0.89,-0.89,-0.89,1.57,3.81,3.81,3.81,3.81,-,0,0,0,0,0,0,0,0.83,1.58,1.58,1.58,1.58,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
151,KAB JAYAWIJAYA,0,0,0,0,0,0,1.82,1.82,1.82,1.82,1.82,1.82,-,0,0,0,0,0,0,2.47,2.47,2.47,2.47,2.47,2.47,-,0,0,0,0,0,0,2.15,2.15,2.15,2.15,2.15,2.15,-,0,0,0,0,0,0,0,0,0,0,0,0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,2024
152,INDONESIA,1.57,1.55,1.7,1.72,1.71,1.69,1.9,1.83,1.94,1.9,1.89,1.94,-,1.77,1.76,1.76,1.76,1.75,1.66,2.1,2.68,2.74,2.72,2.72,2.72,-,1.83,1.83,1.83,1.83,1.83,1.83,1.99,1.51,1.53,1.53,1.53,1.68,-,1.08,1.1,1.1,1.1,1.1,1.1,1.22,1.03,1.33,1.36,1.36,1.36,-,2.09,1.95,3.27,3.46,3.38,3.36,3.62,3.62,3.47,3.12,3.09,3.07,-,2024